### PR TITLE
Start migrating to useraccounts:semantic-ui

### PR DESCRIPTION
**Pull request by rclai**
Here's a work in progress. However, there seems to be an issue with just making a form accepting only a username. It keeps asking for an e-mail implicitly. I posted [an issue](https://github.com/meteor-useraccounts/core/issues/404).

### CODE REVIEW

**Comment by rclai** [comment]
Someone just [gave a solution](https://github.com/meteor-useraccounts/core/issues/404#issuecomment-106573030).

**Comment by rclai** [comment]
Yay, I can log in now with a way nicer login screen :smile:. You can check it out.

**Comment by rclai** [comment]
Address #119.

**Comment by mattfeldman** [comment]
Thank you for picking this, great work!

**Pull request merged**
